server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: microservice-roles-y-permisos
  datasource:
    url: ${ROLES_DB_URL:jdbc:mysql://localhost:3307/microservice-roles-db}
    username: ${ROLES_DB_USERNAME:root}
    password: ${ROLES_DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    loadbalancer:
      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka