server:
  port: 8080
spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: lb://microservice-students
          predicates:
            - Path=/api/v1/students/**
          filters:
            - AuthenticationFilter

        - id: courses
          uri: lb://microservice-courses
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - AuthenticationFilter

        - id: auth
          uri: lb://microservices-auth
          predicates:
            - Path=/api/v1/auth/**

        - id: roles-service
          uri: lb://microservice-roles-y-permisos
          predicates:
            - Path=/api/v1/roles/**
eureka:
  client:
    register-with-eureka: false