server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: microservice-roles-y-permisos
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-roles-db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    loadbalancer:
      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka